name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    
    - name: Install dependencies
      run: forge install
    
    - name: Build contracts
      run: forge build
    
    - name: Run tests
      run: forge test --verbosity 2
    
    - name: Generate gas report
      run: forge test --gas-report > gas-report.txt
    
    - name: Upload gas report
      uses: actions/upload-artifact@v3
      with:
        name: gas-report
        path: gas-report.txt
    
    - name: Run coverage
      run: forge coverage --report lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./lcov.info
        flags: unittests
        name: codecov-umbrella

  audit:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download gas report
      uses: actions/download-artifact@v3
      with:
        name: gas-report
    
    - name: Archive audit artifacts
      run: |
        mkdir -p audit-archive
        cp -r audit/* audit-archive/
        cp gas-report.txt audit-archive/
        tar -czf audit-artifacts.tar.gz audit-archive/
    
    - name: Upload audit artifacts
      uses: actions/upload-artifact@v3
      with:
        name: audit-artifacts
        path: audit-artifacts.tar.gz
